### PR TITLE
Add support to inject baggage propagator headers to the instrumented request

### PR DESCRIPTION
**Pull request by batuhansk**
Refers to the #435 issue

### CODE REVIEW

**Comment by batuhansk** [comment]
> looks like there are some issues in the OSX tests with this PR:
> 
> > /Users/runner/work/opentelemetry-swift/opentelemetry-swift/Tests/OpenTelemetryApiTests/Baggage/Propagation/W3CBaggagePropagatorTest.swift:87: error: -[OpenTelemetryApiTests.W3BaggagePropagatorTest testInject] : XCTAssertTrue failed

I'm on in — will fix it today

**Comment by batuhansk** [comment]
> looks like there are some issues in the OSX tests with this PR:
> 
> > /Users/runner/work/opentelemetry-swift/opentelemetry-swift/Tests/OpenTelemetryApiTests/Baggage/Propagation/W3CBaggagePropagatorTest.swift:87: error: -[OpenTelemetryApiTests.W3BaggagePropagatorTest testInject] : XCTAssertTrue failed

Can we trigger the tests again?

**Comment by batuhansk** [comment]
Can we trigger the tests again? @bryce-b

**Comment by batuhansk** [comment]
The iOS test pipeline took more than 40min, and still seems in progress. Is it normal? @bryce-b 🤔

**Review by bryce-b — APPROVED** [review]

**Review by nachoBonafonte — APPROVED** [review]

**Pull request merged**
