### PR TITLE
Added OtlpTraceJsonExporter and Unit tests

### PR DESCRIPTION
**Pull request by vj4iosdev**
- Added OtlpTraceJsonExporter
- Added Unit Tests for json exporter
- Added OtlpSpan model class

### CODE REVIEW

**Review by nachoBonafonte — COMMENTED** [review]
First of all, thanks for your contribution.
About the PR, it should compile and pass the tests before asking for merging, make it a draft PR if it cannot build or pass tests, you simply want a first review or have any question.
You must also sign the CLA, you can do it by clicking in the `MISSING ID ON COMMIT` in the easycla comment

**Comment by vj4iosdev** [comment]
@nachoBonafonte Thank you for your review and comments. I will make the necessary changes.

**Comment by vj4iosdev** [comment]
@nachoBonafonte Even after signing the CLA document the EasyCLA check is not passing through. Any hints/suggestions on adding the missing ID on a particular commit id?

**Comment by nachoBonafonte** [comment]
> @nachoBonafonte Even after signing the CLA document the EasyCLA check is not passing through. Any hints/suggestions on adding the missing ID on a particular commit id?

It looks like some of the commits are associated with your users and some aren't. You can see in the conversation  that in some of them it shows your avatar and shows `Verified` and in other it just show a generic github icon. I dont know how to solve it, but somehow some of the changes look from other user. Maybe you can try recreating the PR completly from another branch of your repository or something like that. I cannot force the authorization in any way.

**Comment by vj4iosdev** [comment]
> > @nachoBonafonte Even after signing the CLA document the EasyCLA check is not passing through. Any hints/suggestions on adding the missing ID on a particular commit id?
> 
> It looks like some of the commits are associated with your users and some aren't. You can see in the conversation that in some of them it shows your avatar and shows `Verified` and in other it just show a generic github icon. I dont know how to solve it, but somehow some of the changes look from other user. Maybe you can try recreating the PR completly from another branch of your repository or something like that. I cannot force the authorization in any way.

Ok thank you. Let me retry with another branch.

**Pull request closed without merging**
