### PR TITLE
Add GitHub action for testing

### LINKED ISSUE #16: Add a GitHub action to monitor tests
Use Scope for swift for  monitoring tests [https://github.com/marketplace/actions/scope-for-swift](https://github.com/marketplace/actions/scope-for-swift)

### PR DESCRIPTION
**Pull request by nacho-undefinedlabs**
Add GitHub action for testing using Scope
Add Scope badge to Readme file

This will allow us to confirm that all the test passes, help in finding test failure reasons, monitor and handle flaky tests and to historically monitor the performance of the tests. 

This PR also needs to install Scope App: [https://github.com/apps/scope-app](https://github.com/apps/scope-app) in the OpenTelemetry namespace for this repo. Request installation already done. 

Fixes #16

### CODE REVIEW

**Comment by nacho-undefinedlabs** [comment]
Also, configure Scope app for repository access to openTelemetry-swift is needed. It can be done in [https://github.com/apps/scope-app/installations/new](https://github.com/apps/scope-app/installations/new). Thanks

**Comment by SergeyKanzhelev** [comment]
it seems to be configured now

**Comment by nacho-undefinedlabs** [comment]
Hi Sergey, still need one more thing before this PR can be merged and functional. Adding a secret to the repository (I have no permissions) for the configuration of Scope. Is accessible from the namespace in app.scope.dev after logging with a GitHub account but I will write it to you in Gitter.

**Comment by SergeyKanzhelev** [comment]
Added secret:

image

Let me know if I did it right

**Comment by nacho-undefinedlabs** [comment]
Yes, you did it right. I tested this PR in a new branch created to test it and the GH action found the secret and worked es expected and found an issue in the existing code (project is not building correctly). 
Thanks

**Comment by nacho-undefinedlabs** [comment]
I added some changes to fix the build, so now master also builds after this patch. (master is currently broken)
If you approve the PR I will merge it.
Thanks

**Pull request merged**
