### PR TITLE
Exposes OpenTelemetryConcurrency target

### PR DESCRIPTION
**Pull request by NeedleInAJayStack**
Thank you @semicoleon for the excellent changes in https://github.com/open-telemetry/opentelemetry-swift/pull/546! This MR simply exposes the new `OpenTelemetryConcurrency` target through the `OpenTelemetryApi` product so that it is available for usage by downstream packages. This enables usage as shown in [`/Examples/ConcurrencyContext/main.swift`](https://github.com/open-telemetry/opentelemetry-swift/blob/f745a6435bad737dcb29807cd451326f63327a87/Examples/ConcurrencyContext/main.swift).

If you'd prefer for `OpenTelemetryConcurrency` to get its own product, just let me know and I'm happy to adjust. Thanks!

### CODE REVIEW

**Review by bryce-b — APPROVED** [review]

**Comment by NeedleInAJayStack** [comment]
Hmm, kinda strange that the Linux CI appears to be stuck. I'm able to successfully run these tests on a swift:5.10 docker image locally. Any ideas?

**Comment by semicoleon** [comment]
It may just be an intermittent failure, I had quite a few when working on the original PR. There were also a couple of issues with tests never finishing on Linux even when they worked fine on other platforms. I fixed those issues that I encountered but it's possible another one has popped up now.

**Comment by bryce-b** [comment]
Hi @NeedleInAJayStack the concurrency target should be its own product. Adding it to the OpenTelemetryApi product would create a circular dependency.

**Review by nachoBonafonte — CHANGES_REQUESTED** [review]
Please make it a separate product

**Comment by NeedleInAJayStack** [comment]
Sure, I've adjusted it to be a separate product. Thanks!

**Review by bryce-b — APPROVED** [review]

**Comment by NeedleInAJayStack** [comment]
@nachoBonafonte Just a gentle reminder on this PR - any thoughts on my changes? Thanks!

**Review by nachoBonafonte — APPROVED** [review]
Thanks for the reminder, looks good to me now.

**Pull request merged**
