### PR TITLE
:sparkle: added slow frozen rendering instrumentation

### PR DESCRIPTION
**Pull request by Archish27**
feature : #495

### CODE REVIEW

**Comment by bryce-b** [comment]
Can you also add a simple test for this?

**Review by bryce-b — CHANGES_REQUESTED** [review]

**Comment by Sherlouk** [comment]
Does this need adding to the Package.swift too? Looks like it's just loose in Instrumentation/ where others have distinct products.

**Comment by bryce-b** [comment]
@Archish27 This is a good addition, but we have some feedback we'd like you to address.

**Comment by vvydier** [comment]
@Archish27 Any update on this ?

**Pull request closed without merging**
