### PR TITLE
Implement a Stack in the TaskLocal for automatic context handling

### PR DESCRIPTION
**Pull request by nachoBonafonte**
Use a stack in the TaskLocal so we can push and pop context when running in async/await related code.
Added support to running async code also in Xcode 13.2 (still in beta)
Added tests for different context passing scenarios, some of them will only run in Xcode 13.2
Added a name to PropagatedSpan so we can find issues easier when running code

### CODE REVIEW

**Comment by bryce-b** [comment]
I see there are some #ifdefs for swift 5.5.2, but the beta is only saying 5.5.0 is installed. Is there another way to install 5.5.2?

**Comment by nachoBonafonte** [comment]
Xcode 13.2 beta installs swift 5.5.2, doesn’t it?

**Review by SergeyKanzhelev — APPROVED** [review]
mostly glanced thru, looks good.

**Comment by bryce-b** [comment]
If I change the expected swift version in the package file it throws an error if I try to set 5.5.2 saying only 5.5.0 is installed (on beta). Maybe my expectation on how this works is incorrect?

**Comment by nachoBonafonte** [comment]
Package is probably using swift-tools version, which can be a bit different than swift language version. Can you run the tests marked with 5.5.2 using the beta?

**Comment by bryce-b** [comment]
Doesn't seem like the breakpoint will hit within the 5.5.2 ifdef using the beta. Let me try one of the beta toolchains

**Comment by bryce-b** [comment]
AH, turns out there is a difference between `<` & `>`. I was misreading what was happening. Everything looks good.

**Review by bryce-b — APPROVED** [review]

**Pull request merged**
