### PR TITLE
Gauge measurement

### PR DESCRIPTION
**Pull request by bryce-b**

### CODE REVIEW

**Comment by nachoBonafonte** [comment]
It looks good to me, just a pair of very minor comments: Please use the new copyright headers that are now used in all files of the project and check for some extra new lines in some files (xcformat can help)

**Review by nachoBonafonte — CHANGES_REQUESTED** [review]
It looks good to me, just a pair of very minor comments: Please use the new copyright headers that are now used in all files of the project and check for some extra new lines in some files (xcformat can help)

**Review by nachoBonafonte — APPROVED** [review]

**Comment by nachoBonafonte** [comment]
Can you try updating and merging yourself? I think you should be able now being an approver

**Comment by SergeyKanzhelev** [comment]
> Can you try updating and merging yourself? I think you should be able now being an approver

@nachoBonafonte I afraid you will need to merge:

image

It is set up according to the [instruction](https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#:~:text=repository%20must%20enforce%20restrict%20who%20can%20push%20to%20matching%20branches%20setting%20to%20only%20allow%20the%20members%20of%20foo-maintainers%20to%20push%20to%20the%20main%20branch.)

**Pull request merged**
