### PR TITLE
fix race condition in TracerProviderSdk.get when creating a new tracer

### PR DESCRIPTION
**Pull request by seemk**
When multiple threads attempt to get a tracer from tracer provider and the tracer has not yet been constructed, there's a race condition, which usually leads to `EXC_BAD_ACCESS`:

image

As it's hard to create a reliable test case for it, I didn't add a test. However it can be verified by adding the following test to `TracerSdkTests.swift`:

```swift
func testTracerAccess() {
    for i in 0...100000 {
        let name = "abc \(i)"
        for _ in 0...8 {
            let t = Thread(block: {
                let _ = self.tracerSdkFactory.get(instrumentationName: name)
            })
            t.start()
        }
    }
}
```

### CODE REVIEW

**Comment by seemk** [comment]
The error in CI looks to be the same as on main branch 🤔

**Review by nachoBonafonte — APPROVED** [review]
LGTM. Thanks a lot for your contribution.

**Comment by nachoBonafonte** [comment]
Hi Siim,
There is no planned release, but if you need one for deployment I can just prepare one with the current main branch. Just let me know.

**Comment by seemk** [comment]
A new tag would be great, thanks a lot! I believe it was causing rare issues in production

**Comment by nachoBonafonte** [comment]
Its done: [1.1.4](https://github.com/open-telemetry/opentelemetry-swift/releases/tag/1.1.4 )

**Pull request merged**
