### PR TITLE
Addresses sysctl error in DeviceDataSource.model on Mac.

### PR DESCRIPTION
**Pull request by BennettSmith**
When running the `simpleExporter` example on my Mac the output was as follows:

```
error #12: Optional("Cannot allocate memory")
{"spanId":"da090db96f40241a","start":672103345.92109096,"traceId":"91c73b58388077c79f8130dd189a31e7","spanKind":"client","traceState":{"entries":[]},"duration":0.50424504280090332,"parentSpanId":"0000000000000000","span":"SimpleSpan","traceFlags":{"sampled":true},"attributes":{"sampleKey":{"description":"sampleValue"}}}
{"spanId":"5689fa2d6d8bc929","start":672103358.22013605,"traceId":"f256eee6098e430b71582227916ae780","spanKind":"client","traceState":{"entries":[]},"duration":0.50342798233032227,"parentSpanId":"0ddca35bed45ec9a","span":"childSpan","traceFlags":{"sampled":true},"attributes":{"sampleKey":{"description":"sampleValue"}}}
{"spanId":"0ddca35bed45ec9a","start":672103358.01662302,"traceId":"f256eee6098e430b71582227916ae780","spanKind":"client","traceState":{"entries":[]},"duration":0.70706403255462646,"parentSpanId":"0000000000000000","span":"parentSpan","traceFlags":{"sampled":true},"attributes":{"sampleKey":{"description":"sampleValue"}}}
Program ended with exit code: 0
```

Notice the first line that reads `error #12: Optional("Cannot allocate memory")`. This error comes from the `DeviceDataSource.model()` method when the `sysctl` call fails.  The failure is related to the `oldlenp` pointer.

The fix is to call `sysctl` twice. The first call gets the actual buffer size required and then the second call passes the buffer and associated length.

### CODE REVIEW

**Comment by nachoBonafonte** [comment]
Hi @BennettSmith, is the PR ready or still in draft?

**Comment by BennettSmith** [comment]
The PR is ready, but I am waiting on approval from my comapny so we can agree with the CLA.  I will set it back to a draft for now.

**Comment by BennettSmith** [comment]
@nachoBonafonte The build for this PR is failing, but I'm at a loss to see how the failure is related to the changes.  Could this be a case of a flaky test?

**Comment by nachoBonafonte** [comment]
Yes, re-running until green and will merge

**Review by nachoBonafonte — APPROVED** [review]
LGTM. Thanks a lot for your contribution.

**Pull request merged**
