### PR TITLE
Synchronize access race in HistogramMetric

### PR DESCRIPTION
**Pull request by angelodipaolo**
Fixes https://github.com/open-telemetry/opentelemetry-swift/issues/608

### CODE REVIEW

**Comment by bryce-b** [comment]
@angelodipaolo,
Thanks for the contribution! Before we can merge your changes can you please sign the CLA? The link to do so was linked above.

**Comment by angelodipaolo** [comment]
Hi @bryce-b, yes I'm working with my legal partners here at eBay to get the CLA signed. I left this in a draft state while I for the process to complete.

**Review by vvydier — APPROVED** [review]

**Comment by bryce-b** [comment]
@angelodipaolo any progress on getting the CLA signed?

**Comment by angelodipaolo** [comment]
@bryce-b thanks for the nudge! I was able to get the CLA signed

**Pull request merged**
