### PR TITLE
Added OtlpTraceJsonExporter and Unit Tests

### PR DESCRIPTION
**Pull request by vj4iosdev**
- Added OtlpTraceJsonExporter
- Added OtlpSpan model
- Added Unit Test

### CODE REVIEW

**Review by nachoBonafonte — CHANGES_REQUESTED** [review]
LGTM, please update with main branch by clicking the `Update branch` button at the PR and fix any conflict that may happen. 
After that I will approve and merge

**Review by nachoBonafonte — APPROVED** [review]

**Comment by nachoBonafonte** [comment]
I will merge your PR now, thanks a lot for your contribution.

**Comment by vj4iosdev** [comment]
> I will merge your PR now, thanks a lot for your contribution.

Awesome @nachoBonafonte Thanks for quick review. Really appreciate.

**Comment by nachoBonafonte** [comment]
Fixes #110

**Comment by nachoBonafonte** [comment]
Please close the related issue you opened if it is really solved. And feel free to help with any other existing issue or propose any.

**Comment by vj4iosdev** [comment]
Yes it did the solve the issue. Closed the issue. 
Surely will update, if any issues I find or any new things, I will contribute to the repo.

**Pull request merged**
